### ISSUE TITLE
Required keyword arguments in block raise exception.

### ISSUE THREAD

**Issue by cvortmann** [seattlerb/ruby_parser#180]
Using:
  * rubycritic (1.4.0)
  * flog (4.2.1)
  * ruby_parser (3.6.5)

This code runs fine:
```
def method_name(required_keyword_argument:)
end
```

But this code raises an exception:
```
def method_name(required_keyword_argument:)
  required_keyword_argument.each { |required_block_keyword_argument:| }
end
```

Running rubycritic for a file called `raises_exception.rb` with the second snippet:

```
$ rubycritic raises_exception.rb

RubyCritic can provide more feedback if you use a Git or Mercurial repository.
  fuck 11
  skipping raises_exception.rb
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.5/lib/ruby21_parser.rb:6482:in `_reduce_561': fuck 11 (RuntimeError)
	~/.rbenv/versions/2.1.5/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
	~/.rbenv/versions/2.1.5/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1036:in `block in process'
	~/.rbenv/versions/2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	~/.rbenv/versions/2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
	~/.rbenv/versions/2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	~/.rbenv/versions/2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	~/.rbenv/versions/2.1.5/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1024:in `process'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1357:in `block in process'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1355:in `each'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1355:in `process'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flog-4.2.1/lib/flog.rb:219:in `flog_ruby!'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flog-4.2.1/lib/flog.rb:189:in `flog_ruby'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flog-4.2.1/lib/flog.rb:177:in `block in flog'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flog-4.2.1/lib/flog.rb:172:in `each'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flog-4.2.1/lib/flog.rb:172:in `flog'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/analysers/smells/flog.rb:26:in `add_smells_to'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/analysers/smells/flog.rb:18:in `block in run'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/analysers/smells/flog.rb:17:in `each'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/analysers/smells/flog.rb:17:in `run'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/analysers_runner.rb:27:in `block in run'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/analysers_runner.rb:27:in `each'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/analysers_runner.rb:27:in `run'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/commands/default.rb:19:in `critique'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/commands/default.rb:15:in `execute'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/lib/rubycritic/cli/application.rb:16:in `execute'
	~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubycritic-1.4.0/bin/rubycritic:5:in `<top (required)>'
	~/.rbenv/versions/2.1.5/bin/rubycritic:23:in `load'
	~/.rbenv/versions/2.1.5/bin/rubycritic:23:in `<main>'
```

**Comment by ivanoblomov** [comment]
We've been seeing this error for a while now too and only realized recently it was coming from ruby_parser. Here's the scurrilous line...

https://github.com/seattlerb/ruby_parser/blob/master/lib/ruby21_parser.y#L2175

**Comment by bankair** [comment]
Best raise ever :)

**Comment by zenspider** [comment]
Minimal repro:

```ruby
blah { |kwarg:| }
```

Perfect. Thanks for the report!

**Comment by zenspider** [comment]
Just fixed this. Should get released soon. Thanks!

**Comment by bf4** [comment]
Fixed by https://github.com/seattlerb/ruby_parser/commit/a1750d474c4309a9166afc63cfcde35a6f8241ad
