### ISSUE TITLE
Error parsing file containint method modifiers.

### ISSUE THREAD

**Issue by MartynasM** [seattlerb/ruby_parser#185]
[Originated as FLOG issue](https://github.com/seattlerb/flog/issues/54)
File items.rb
```ruby
require 'memoist'

class Test
  extend Memoist
  memoize def method_name
    collection.map_by(:id) do |item|
    end
  end
end
```
``` 
~$ ruby --version
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-linux]

~$ gem install ruby_parser
Fetching: ruby_parser-3.6.6.gem (100%)
Successfully installed ruby_parser-3.6.6
~$ ruby_parse items.rb 
# file = items.rb loc = 9
/home/bugo/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/racc/parser.rb:529:in `on_error' #<Racc::ParseError: items.rb:6 :: parse error on value ["do", 6] (kDO_BLOCK)> for items.rb
  /home/bugo/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/racc/parser.rb:529:in `on_error'
  /home/bugo/.rvm/gems/ruby-2.1.4/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1124:in `on_error'
  /home/bugo/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
  /home/bugo/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
  /home/bugo/.rvm/gems/ruby-2.1.4/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1036:in `block in process'
  /home/bugo/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
  /home/bugo/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
  /home/bugo/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:35:in `catch'
  /home/bugo/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:35:in `catch'
  /home/bugo/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
  /home/bugo/.rvm/gems/ruby-2.1.4/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1024:in `process'
  /home/bugo/.rvm/gems/ruby-2.1.4/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1357:in `block in process'
  /home/bugo/.rvm/gems/ruby-2.1.4/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1355:in `each'
  /home/bugo/.rvm/gems/ruby-2.1.4/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1355:in `process'
  /home/bugo/.rvm/gems/ruby-2.1.4/gems/ruby_parser-3.6.6/bin/ruby_parse:48:in `block in <top (required)>'
  /home/bugo/.rvm/gems/ruby-2.1.4/gems/ruby_parser-3.6.6/bin/ruby_parse:29:in `each'
  /home/bugo/.rvm/gems/ruby-2.1.4/gems/ruby_parser-3.6.6/bin/ruby_parse:29:in `<top (required)>'
  /home/bugo/.rvm/gems/ruby-2.1.4/bin/ruby_parse:23:in `load'
  /home/bugo/.rvm/gems/ruby-2.1.4/bin/ruby_parse:23:in `<main>'
  /home/bugo/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
  /home/bugo/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
done

 0.00s:  2853.80 l/s:   39.64 Kb/s:    0 Kb:    9 loc:TOTAL
```

**Comment by zenspider** [comment]
Fixed.
