### ISSUE TITLE
Parse failure involving single-method private and do/end block

### ISSUE THREAD

**Issue by dschweisguth** [seattlerb/ruby_parser#187]
```
> ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
> cat private_error.rb 
require 'ruby_parser'

RubyParser.new.parse %q(
  class X
    def foo
      { key: :value }
    end

    private def traverse(list)
      list.each do |item| end
    end

  end
)
> ruby private_error.rb 
/Users/me/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:128:in `syntax_error': Odd number (2) list for Hash. s(:array, s(:call, nil, :key)) (RubyParser::SyntaxError)
	from /Users/schwa/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.6/lib/ruby18_parser.rb:5685:in `_reduce_492'
# ...
```
`ruby -w` on class X in its own file reports no problems.

Removing method `foo`, or just deleting its contents, produces this error instead:
```
/Users/me/.rbenv/versions/2.1.6/lib/ruby/2.1.0/racc/parser.rb:529:in `on_error': (string):4 :: parse error on value ["do", 4] (kDO_BLOCK) (Racc::ParseError)
	from /Users/schwa/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1124:in `on_error'
```

Removing `private`, putting it on its own line, or replacing `do` and `end` with `{` and `}` all eliminate the error.

**Comment by dschweisguth** [comment]
Just noticed that the first error was in ruby18_parser.rb. Trying again with current Ruby:

```
> cat private_error.rb 
require 'ruby_parser'

RubyParser.for_current_ruby.parse %q(
  class X
    def foo
      { key: :value }
    end

    private def traverse(list)
      list.each do |item| end
    end

  end
)
> ruby private_error.rb 
/Users/me/.rbenv/versions/2.1.6/lib/ruby/2.1.0/racc/parser.rb:529:in `on_error': (string):8 :: parse error on value ["do", 8] (kDO_BLOCK) (Racc::ParseError)
	from /Users/me/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1124:in `on_error'
```
Removing or eviscerating `foo` no longer makes a difference. Hitting newline after or removing `private` or replacing do/end with curlies still eliminates the error.

**Comment by zenspider** [comment]
The 1.8 issue is just misdirection. The real parse error (`private def`) is the only concern here.

**Comment by zenspider** [comment]
Minimal repro:

```ruby
private def a
          a.b do end
        end
```

**Comment by dschweisguth** [comment]
Confirmed fixed in https://github.com/seattlerb/ruby_parser/commit/adeceebf04f03bd0a878201fbf5979111acaa26f
