### ISSUE TITLE
Parse failure involving trailing-colon hash key and newline

### ISSUE THREAD

**Issue by dschweisguth** [seattlerb/ruby_parser#188]
```
$ ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
[06:45:23 ~/data/projects/IndieGoGo] cat key_newline_error.rb 
require 'ruby_parser'

RubyParser.for_current_ruby.parse %q(
  class X
    def x
      { key: 
        :value }
    end
  end
)
$ ruby key_newline_error.rb 
/Users/me/.rbenv/versions/2.1.6/lib/ruby/2.1.0/racc/parser.rb:529:in `on_error': (string):5 :: parse error on value nil (tNL) (Racc::ParseError)
	from /Users/schwa/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1124:in `on_error'
```

`ruby -w` on class X in its own file reports no problems.

Replacing `key:` with `:key =>` or removing the newline after `key:` fixes the error.

**Comment by dschweisguth** [comment]
Confirmed fixed in https://github.com/seattlerb/ruby_parser/commit/adeceebf04f03bd0a878201fbf5979111acaa26f
