### ISSUE TITLE
Ternary failure: a ? '': b

### ISSUE THREAD

**Issue by presidentbeef** [seattlerb/ruby_parser#191]
Not sure what's going on here. When I install ruby_parser as a gem (with https://gist.github.com/zenspider/a18f2c57518b0d802fc4), I get this error. But when I run the tests I can't get it to fail! Not sure what's going on.

```
$ cat out.rb 
a ? '': b
$ ruby_parse out.rb 
# file = out.rb loc = 1
/home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_lexer.rb:653:in `process_symbol' #<NoMethodError: undefined method `gsub' for nil:NilClass> for out.rb
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_lexer.rb:653:in `process_symbol'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_lexer.rb:662:in `process_label'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_lexer.rex.rb:169:in `next_token'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:919:in `next_token'
  /home/justin/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
  /home/justin/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1036:in `block in process'
  /home/justin/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
  /home/justin/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
  /home/justin/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `catch'
  /home/justin/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `catch'
  /home/justin/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1024:in `process'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1362:in `block in process'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1360:in `each'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/lib/ruby_parser_extras.rb:1360:in `process'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/bin/ruby_parse:48:in `block in <top (required)>'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/bin/ruby_parse:29:in `each'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/gems/ruby_parser-3.6.6/bin/ruby_parse:29:in `<top (required)>'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/bin/ruby_parse:23:in `load'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/bin/ruby_parse:23:in `<main>'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/bin/ruby_executable_hooks:15:in `eval'
  /home/justin/.rvm/gems/ruby-2.1.5@ruby_parser/bin/ruby_executable_hooks:15:in `<main>'
done
```

I tried to add this to test_ruby_lexer.rb, but it passed:
```ruby
  def test_yylex_ternary2
    assert_lex3("a ? '': b",
                nil,
                :tIDENTIFIER, "a", :expr_cmdarg,
                :tEH,         "?", :expr_value,
                :tSTRING,     "", :expr_end,
                :tCOLON,      ":", :expr_beg,
                :tIDENTIFIER, "b", :expr_arg)
  end
```

Then I tried to add this to test_ruby_parser.rb just to double check:
```ruby
  def test_ternary_symbol
    assert_parse "a ? '': b", s()
  end
```
But it parsed.

I don't know what's happening. Maybe I need caffeine.

**Comment by presidentbeef** [comment]
To clarify, this also happens with master, not just with the patch from the gist.

**Comment by zenspider** [comment]
> On Apr 28, 2015, at 08:54, Justin <notifications@github.com> wrote:
> 
> $ cat out.rb 
> a ? '': b
> $ ruby_parse out.rb 
> # file = out.rb loc = 1

It's times like this when I hate you. :P

**Comment by presidentbeef** [comment]
I knew you would be thrilled!

**Comment by zenspider** [comment]
This fails for me:

```ruby
  def test_bug191
    rb = "a ? '': b"
    pt = 42

    assert_parse rb, pt
  end
```

I put it in `TestRuby22Parser` and I get the same gsub/nil issue you get. Maybe it was where you put the test case? I dunno. Looking now.

**Comment by zenspider** [comment]
Fixed. Thanks!

**Comment by presidentbeef** [comment]
Thank you!

Now if I could only remember where this code came from...
