### ISSUE TITLE
Fails to parse method defined with `private_class_method` containing block using `do`

### ISSUE THREAD

**Issue by carbonin** [seattlerb/ruby_parser#213]
Using the following version of ruby and ruby_parser:
`ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]`
`ruby_parser (3.8.1)`

I parsed the two following example files using:

``` ruby
RubyParser.for_current_ruby.parse(File.read(path))
```

This example file will parse:

``` ruby
class Works
  def self.calls_meth
    meth
  end

  def self.meth
    [1,2,3].each do |i|
      puts i
    end
  end
  private_class_method :meth
end

Works.calls_meth
```

While this one fails:

``` ruby
class Fails
  def self.calls_meth
    meth
  end

  private_class_method def self.meth
    [1,2,3].each do |i|
      puts i
    end
  end
end

Fails.calls_meth
```

This is the backtrace that results from parsing the failing file:

``` plain
/home/ncarboni/.rubies/ruby-2.2.4/lib/ruby/2.2.0/racc/parser.rb:527:in `on_error': (string):7 :: parse error on value ["do", 7] (kDO_BLOCK) (Racc::ParseError)
    from /home/ncarboni/.gem/ruby/2.2.4/gems/ruby_parser-3.8.1/lib/ruby_parser_extras.rb:1125:in `on_error'
    from /home/ncarboni/.rubies/ruby-2.2.4/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
    from /home/ncarboni/.rubies/ruby-2.2.4/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
    from /home/ncarboni/.gem/ruby/2.2.4/gems/ruby_parser-3.8.1/lib/ruby_parser_extras.rb:1037:in `block in process'
    from /home/ncarboni/.rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
    from /home/ncarboni/.rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
    from /home/ncarboni/.rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:32:in `catch'
    from /home/ncarboni/.rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:32:in `catch'
    from /home/ncarboni/.rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
    from /home/ncarboni/.gem/ruby/2.2.4/gems/ruby_parser-3.8.1/lib/ruby_parser_extras.rb:1025:in `process'
    from parse.rb:6:in `<main>'
```

**Comment by zenspider** [comment]
I really hope we don't start writing ruby that way. Horrible.

**Comment by phorsuedzie** [comment]
Have seen that one too (even though only once :-).

> I really hope we don't start writing ruby that way. Horrible.

To prefix a method with visibility helps to have a small diff when changing visibility (e.g. because the method get wrapped).

And, without a `class << self` section, this reduces the both LOC and duplication to declare a singleton method `private`.

**Comment by zenspider** [comment]
See: `private_class_method`

**Comment by zenspider** [comment]
This is fixed. Thanks!
