### ISSUE TITLE
RubyParser.new.parse returns different results between 3.6.6 and 3.7.0

### ISSUE THREAD

**Issue by annaswims** [seattlerb/ruby_parser#219]
I'm afraid I'm at the end of my understanding, but it looks like  `RubyParser.new.parse()` returns different results for 3.6.6 and 3.7.0.  The `do`'s become `0`'s

```
gem 'ruby_parser', '3.6.6'
=> true
require 'ruby_parser'
=> true
rules = "      authorization do\n        role :test_role do\n        end\n      end"
=> "      authorization do\n        role :test_role do\n        end\n      end"
sexp_array = RubyParser.new.parse(rules)
=> s(:iter, s(:call, nil, :authorization), s(:args), s(:iter, s(:call, nil, :role, s(:lit, :test_role)), s(:args)))
```

```
gem 'ruby_parser', '3.7.0'
=> true
require 'ruby_parser'
=> true
rules = "      authorization do\n        role :test_role do\n        end\n      end"
=> "      authorization do\n        role :test_role do\n        end\n      end"
sexp_array = RubyParser.new.parse(rules)
=> s(:iter, s(:call, nil, :authorization), 0, s(:iter, s(:call, nil, :role, s(:lit, :test_role)), 0))
```

**Comment by zenspider** [comment]
This is true. In the release notes for 3.7.0:

```markdown
  * Fixed handling of block_args to be consistent across all parse versions.
```

The `0` is for "strict args" handling. IOW, distinguishing between optionally zero args and strictly zero args.

Where are you seeing a problem. If there is some way I can help, please let me know.

**Comment by annaswims** [comment]
Thanks for the response.  

I'm using the declarative_authorization gem and 4 tests fail similarly with ruby_parser <= 3.7

It looks like the root cause is https://github.com/stffn/declarative_authorization/blob/master/lib/declarative_authorization/development_support/analyzer.rb#L160  I'll dig into it an see if I can figure it out. 


````
 AuthorizationRulesAnalyzerTest#test_analyze_for_proposed_privilege_hierarchy:
NoMethodError: undefined method `first' for 0:Fixnum
    /Users/annacarey/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/sexp_processor-4.7.0/lib/sexp_processor.rb:223:in `process'
    /Users/annacarey/Developer/code/source/declarative_authorization/lib/declarative_authorization/development_support/analyzer.rb:161:in `process_iter'
    /Users/annacarey/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/sexp_processor-4.7.0/lib/sexp_processor.rb:251:in `block (2 levels) in process'
    /Users/annacarey/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/sexp_processor-4.7.0/lib/sexp_processor.rb:308:in `error_handler'
    /Users/annacarey/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/sexp_processor-4.7.0/lib/sexp_processor.rb:250:in `block in process'
    /Users/annacarey/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/sexp_processor-4.7.0/lib/sexp_processor.rb:373:in `in_context'
    /Users/annacarey/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/sexp_processor-4.7.0/lib/sexp_processor.rb:227:in `process'
    /Users/annacarey/Developer/code/source/declarative_authorization/lib/declarative_authorization/development_support/analyzer.rb:152:in `analyze'
    /Users/annacarey/Developer/code/source/declarative_authorization/lib/declarative_authorization/development_support/analyzer.rb:29:in `block in analyze'
    /Users/annacarey/Developer/code/source/declarative_authorization/lib/declarative_authorization/development_support/analyzer.rb:28:in `each'
    /Users/annacarey/Developer/code/source/declarative_authorization/lib/declarative_authorization/development_support/analyzer.rb:28:in `analyze'
    /Users/annacarey/Developer/code/source/declarative_authorization/test/development_support/analyzer_test.rb:275:in `engine_analyzer_for'
    /Users/annacarey/Developer/code/source/declarative_authorization/test/development_support/analyzer_test.rb:250:in `test_analyze_for_proposed_privilege_hierarchy'
````

**Comment by zenspider** [comment]
The *real* bug is that declarative_authorization doesn't seem to declare any gem dependencies. 

I've filed a bug here: https://github.com/stffn/declarative_authorization/issues/215

There's a secondary bug in that the gem isn't handling the data properly... but until we know what version is actually intended to be used... probably shouldn't bother with it yet.

I assume you have your own dependencies declared in a gemfile somewhere. Is it possible to fix your versions to the combination that works for you for now?

**Comment by annaswims** [comment]
Using ruby_parser 3.6.6 works for me.  Thanks!  It's been almost 2 years since a commit to declarative_authorization master, despite numerous PR's so I think I'll have to let it go there.

**Comment by zenspider** [comment]
Please close if this is resolved.
