### ISSUE TITLE
Parse error: self.new(connection, *, parent: nil, **)

### ISSUE THREAD

**Issue by oreoshake** [seattlerb/ruby_parser#224]
I don't even know what that code does, but apparently it's valid ruby that `ruby_parser` doesn't like.

```
RubyParser.new.parse("class A\nself.new(connection, *, parent: nil, **)\nend\nend")

Racc::ParseError: (string):2 :: parse error on value "," (tCOMMA)
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/2.1.0/racc/parser.rb:529:in `on_error'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/gems/2.1.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1165:in `on_error'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/gems/2.1.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1077:in `block in process'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/2.1.0/timeout.rb:33:in `block in catch'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/2.1.0/timeout.rb:33:in `catch'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/2.1.0/timeout.rb:33:in `catch'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/2.1.0/timeout.rb:105:in `timeout'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/gems/2.1.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1065:in `process'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/gems/2.1.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1408:in `block in process'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/gems/2.1.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1406:in `each'
    from /Users/neil/.rbenv/versions/2.1.7-github/lib/ruby/gems/2.1.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1406:in `process'
    from (irb):2
```

/cc @gregose @ptoomey3 @brentjo @presidentbeef @zenspider

**Comment by presidentbeef** [comment]
The provided example has an extra `end`. Was it supposed to be a method call or a method definition?

I'm fairly certain you can't have a bare `**` in a method call:

```
2.4.0 :001 > x(**)
SyntaxError: (irb):1: syntax error, unexpected ')'
x(**)
     ^
	from /home/justin/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'
```

If it was meant to be a method definition, ruby_parser handles that fine now:

```
2.4.0 :002 > RubyParser.new.parse "def self.new(connection, *, parent: nil, **) end"
 => s(:defs, s(:self), :new, s(:args, :connection, :*, s(:kwarg, :parent, s(:nil)), :**), s(:nil))
```

**Comment by zenspider** [comment]
I'm closing this. There doesn't seem to be a repro

```
% rake debug R="class A;self.new(connection, *, parent: nil, **);end;end"
#<Racc::ParseError: env:1 :: parse error on value "," (tCOMMA)>
on env:1
% ruby -cwe "class A;self.new(connection, *, parent: nil, **);end;end"
-e:1: syntax error, unexpected ','
lass A;self.new(connection, *, parent: nil, **);end;end
                              ^
-e:1: Can't assign to nil
ew(connection, *, parent: nil, **);end;end
```

versus

```
rake debug R="class A;def self.new(connection, *, parent: nil, **);end;end"
s(:class,
 :A,
 nil,
 s(:defs,
  s(:self),
  :new,
  s(:args, :connection, :*, s(:kwarg, :parent, s(:nil)), :**),
  s(:nil)))
```

**Comment by oreoshake** [comment]
Yeah, this error has gone away. for reference here is the actual code:

```ruby
module Plumbus
  module Floobelcrank
    class Foo
      def self.new(connection, *, parent: nil, **)
        connection.parent = parent
        connection
      end
    end
  end
end
```
