### ISSUE TITLE
Parse error on destructuring block argument

### ISSUE THREAD

**Issue by ryota-ka** [seattlerb/ruby_parser#232]
``` ruby
foo { |(*xs, x)| bar }
```

This code snippet cannot be parsed although `ruby -c` passes.
It seems to be a problem around block argument destructuring with parentheses.
(without parens, the code above can be parsed but it sometimes could be like `|(*xs, x), y|`)

Error messages:

```
# file = ./foo.rb loc = 1
/Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:107:in `debug20' #<RuntimeError: not yet 17 ["*", :xs, ",", s(:array, :x)] => s(:masgn, :"*xs", :x)> for ./foo.rb
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:107:in `debug20'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/lib/ruby23_parser.rb:5330:in `_reduce_368'
  /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/racc/parser.rb:259:in `do_parse'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1077:in `block in process'
  /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
  /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
  /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
  /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
  /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1065:in `process'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1408:in `block in process'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1406:in `each'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1406:in `process'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/bin/ruby_parse:48:in `block in <top (required)>'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/bin/ruby_parse:29:in `each'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/gems/ruby_parser-3.8.2/bin/ruby_parse:29:in `<top (required)>'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/bin/ruby_parse:24:in `load'
  /Users/Ryota/dev/rubyp/vendor/bundle/ruby/2.3.0/bin/ruby_parse:24:in `<main>'
done



 0.00s:   374.53 l/s:    8.41 Kb/s:    0 Kb:    1 loc:TOTAL
```

**Comment by zenspider** [comment]
This has been fixed for some time. Closing.
