### ISSUE TITLE
Parse error in some methods with argument and do-block containing rescue

### ISSUE THREAD

**Issue by maisumakun** [seattlerb/ruby_parser#265]
The following code cannot be parsed even in `Ruby25Parser`.

```ruby
open 'filename' do |f|
  f.read
rescue IOError
  nil
end
```

tested in IRB:

```
irb(main):009:0> Ruby25Parser.new.parse("open 'filename' do |f|\nf.read\nrescue IOError\nnil\nend")
Traceback (most recent call last):
       13: from /home/user/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
       12: from (irb):9
       11: from /home/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1070:in `process'
       10: from /home/user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
        9: from /home/user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:33:in `catch'
        8: from /home/user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:33:in `catch'
        7: from /home/user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
        6: from /home/user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
        5: from /home/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1082:in `block in process'
        4: from /home/user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/racc/parser.rb:259:in `do_parse'
        3: from /home/user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/racc/parser.rb:259:in `_racc_do_parse_c'
        2: from /home/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1175:in `on_error'
        1: from /home/user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/racc/parser.rb:528:in `on_error'
Racc::ParseError ((string):3 :: parse error on value ["rescue", 3] (kRESCUE))
```

## Versions

* ruby-parser 3.11.0
* Ruby `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`
* Environment Linux (machine name) 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by presidentbeef** [comment]
This was just addressed here: https://github.com/seattlerb/ruby_parser/commit/05cfb5456e91e4ecefae8f3d253153639293b52c

**Comment by zenspider** [comment]
This is a duplicate and is fixed.
