### ISSUE TITLE
ActiveRecord scope extension parse error

### ISSUE THREAD

**Issue by issei126** [seattlerb/ruby_parser#266]
The related issue https://github.com/presidentbeef/brakeman/issues/1245

When I use rubocop for the under code, a parse error occured.

```
class Company
  scope :retired_employees, -> do
     where(status: :retired)
  end do
    def find_or_create_by_name(name)
      first_name, last_name = name.split(" ", 2)
      find_or_create_by(first_name: first_name, last_name: last_name)
    end
  end
end
```

shown error
```
$ ruby_parse sample.rb
# file = sample.rb loc = 9
/Users/issei/.rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:528:in `on_error' #<Racc::ParseError: sample.rb:2 :: parse error on value nil (error)> for sample.rb
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:528:in `on_error'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1175:in `on_error'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1082:in `block in process'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1070:in `process'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.11.0/lib/ruby_parser.rb:31:in `block in process'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.11.0/lib/ruby_parser.rb:28:in `each'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.11.0/lib/ruby_parser.rb:28:in `process'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.11.0/bin/ruby_parse:48:in `block in <top (required)>'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.11.0/bin/ruby_parse:29:in `each'
  /Users/issei/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.11.0/bin/ruby_parse:29:in `<top (required)>'
  /Users/issei/.rbenv/versions/2.4.1/bin/ruby_parse:22:in `load'
  /Users/issei/.rbenv/versions/2.4.1/bin/ruby_parse:22:in `<main>'
done


 0.01s:  1096.49 l/s:   30.82 Kb/s:    0 Kb:    9 loc:sample.rb

 0.01s:  1096.49 l/s:   30.82 Kb/s:    0 Kb:    9 loc:TOTAL
```

Additionaly, the above code is valid Ruby code.

```
ruby -c sample.rb
Syntax OK
```

A code like that is introduced in the APIDocs.
https://apidock.com/rails/ActiveRecord/Scoping/Named/ClassMethods/scope

>  Named scopes can also have extensions, just as with has_many declarations:

```
class Shirt < ActiveRecord::Base
  scope :red, -> { where(color: 'red') } do
    def dom_id
      'red_shirts'
    end
  end
end
```

**Comment by zenspider** [comment]
This is fixed.
