### ISSUE TITLE
: parse error on value ":" (tCOLON)

### ISSUE THREAD

**Issue by sonalkr132** [seattlerb/ruby_parser#278]
### Background

Brakeman version: 4.4.0
ruby_parser version: 3.12.0
Rails version: 5.2.2
Ruby version: 2.5.3

Link to Rails application code:
https://github.com/rubygems/rubygems.org/blob/master/app/models/concerns/rubygem_searchable.rb#L10

### Issue
```
Error: /home/travis/build/rubygems/rubygems.org/app/models/concerns/rubygem_searchable.rb:10 :: parse error on value ":" (tCOLON)
Location: Could not parse /home/travis/build/rubygems/rubygems.org/app/models/concerns/rubygem_searchable.rb
```
code at rubygem_searchable.rb:10: `delegate :index_document, to: :__elasticsearch__`
Build: https://travis-ci.org/rubygems/rubygems.org/jobs/481288642#L1655
#### Other Error
```
$ ruby_parse app/models/concerns/rubygem_searchable.rb 
# file = app/models/concerns/rubygem_searchable.rb loc = 135
/home/aditya/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/racc/parser.rb:528:in `on_error' #<Racc::ParseError: app/models/concerns/rubygem_searchable.rb:10 :: parse error on value ":" (tCOLON)> for app/models/concerns/rubygem_searchable.rb
/home/aditya/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/racc/parser.rb:528:in `on_error'                                                                                  
  /home/aditya/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/lib/ruby_parser_extras.rb:1175:in `on_error'                                                               
  /home/aditya/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/racc/parser.rb:259:in `_racc_do_parse_c'                                                                          
  /home/aditya/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/racc/parser.rb:259:in `do_parse'                                                                                  
  /home/aditya/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/lib/ruby_parser_extras.rb:1082:in `block in process'                                                       
  /home/aditya/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'                                                                               
  /home/aditya/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'                                                                                 
  /home/aditya/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/timeout.rb:33:in `catch'                                                                                          
  /home/aditya/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/timeout.rb:33:in `catch'                                                                                          
  /home/aditya/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/timeout.rb:108:in `timeout'                                                                                       
  /home/aditya/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/lib/ruby_parser_extras.rb:1070:in `process'                                                                
  /home/aditya/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/lib/ruby_parser.rb:35:in `block in process'                                                                
  /home/aditya/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/lib/ruby_parser.rb:32:in `each'
  /home/aditya/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/lib/ruby_parser.rb:32:in `process'
  /home/aditya/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/bin/ruby_parse:48:in `block in <top (required)>'
  /home/aditya/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/bin/ruby_parse:29:in `each'
  /home/aditya/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/bin/ruby_parse:29:in `<top (required)>'
  /home/aditya/.rvm/gems/ruby-2.5.3/bin/ruby_parse:23:in `load'
  /home/aditya/.rvm/gems/ruby-2.5.3/bin/ruby_parse:23:in `<main>'
  /home/aditya/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
  /home/aditya/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
done
```

**Comment by presidentbeef** [comment]
This the error described in #272.

The rubygems.org code actually at fault [is here](https://github.com/rubygems/rubygems.org/blob/master/app/models/concerns/rubygem_searchable.rb#L64-L66):

```ruby
    def self.elastic_search(query) # rubocop:disable Metrics/MethodLength
      search_definition = Elasticsearch::DSL::Search.search do
        query do
          function_score do
            query do
              bool do
                # Main query, search in name, summary, description
                should do
                  query_string do
                    query query
```

As you can see, `query` is both a local variable (as a method argument) and a method name.

In my opinion, that's kind of weird and confusing.

**Comment by sonalkr132** [comment]
Thank you for debugging this. I have fixed `query query` issue [here](https://github.com/rubygems/rubygems.org/pull/1633/files#diff-12586d7f7d4280aacf2eda990a65f636R31).
Closing this as dup.
